name: Container Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Podman Login
      uses: redhat-actions/podman-login@v1.6
      with:
        # Hostname/domain of the container image registry such as quay.io, docker.io
        registry: cr.srock.cc
        # Username to log in against the container image registry
        username: robot$torad_github
        # Password, encrypted password, or access token for username
        password: ${{ secrets.SHAMROCK_REGISTRY_ROBOT_SECRET }}
        # Path of the authentication file, this will override the default auth file path in podman
        #auth_file_path: # optional
        # 'By default, the action logs out of the container image registry at the end of the job (for self-hosted runners). Set this to false to disable this behaviour'
        logout: true # optional, default is true
    - name: Buildah Build
      uses: redhat-actions/buildah-build@v2.12
      with:
        # The name (reference) of the image to build
        image: torad/user-info # optional
        # The tags of the image to build. For multiple tags, seperate by whitespace. For example, "latest v1".
        tags: latest ${{ github.ref_name }} # optional, default is latest
        # The labels of the image to build. Seperate by newline. For example, "io.containers.capabilities=sys_admin,mknod".
        #labels: # optional
        # The base image to use to create a new container image
        #base-image: # optional
        # List of Containerfile paths (eg: ./Containerfile)
        containerfiles: ./Containerfile # optional
        # Alias for "containerfiles". "containerfiles" takes precedence if both are set.
        #dockerfiles: # optional
        # Path of the directory to use as context (default: .)
        context: . # optional, default is .
        # List of files/directories to copy inside the base image
        #content: # optional
        # The entry point to set for containers based on image
        #entrypoint: # optional
        # Set to true to cache intermediate layers during build process
        #layers: # optional
        # The port to expose when running containers based on image
        #port: # optional
        # The working directory to use within the container
        #workdir: # optional
        # List of environment variables to be set when running containers based on image
        #envs: # optional
        # List of --build-args to pass to buildah
        #build-args: # optional
        # Set to true to build using the OCI image format instead of the Docker image format
        #oci: # optional, default is false
        # Label the image with this ARCH, instead of defaulting to the host architecture
        #arch: # optional
        # 'Same as input 'arch', use this for multiple architectures. Seperate them by a comma'
        #archs: # optional
        # Label the image with this PLATFORM, instead of defaulting to the host platform. Only supported for containerfile builds.
        #platform: # optional
        # 'Same as input 'platform', use this for multiple platforms. Seperate them by a comma'
        #platforms: # optional
        # Extra args to be passed to buildah bud and buildah from. Separate arguments by newline. Do not use quotes - @actions/exec will do the quoting for you.
        #extra-args: # optional
        # Require HTTPS and verify certificates when accessing the registry. Defaults to true.
        tls-verify: true # optional, default is true
    - name: Push To Registry
      uses: redhat-actions/push-to-registry@v2.7
      with:
        # Name of the image/manifest to push (e.g. username/imagename or imagename)
        image: torad/user-info # optional
        # 'The tag or tags of the image/manifest to push. For multiple tags, seperate by whitespace. For example, "latest v1"'
        tags: latest ${{ github.ref_name }} # optional, default is latest
        # Hostname and optional namespace to push the image to (eg. quay.io/username or quay.io)
        registry: cr.srock.cc # optional
        # Username to use as credential to authenticate to the registry
        username: robot$torad_github # optional
        # Password to use as credential to authenticate to the registry
        password: ${{ secrets.SHAMROCK_REGISTRY_ROBOT_SECRET }} # optional
        # Verify TLS certificates when contacting the registry
        tls-verify: true # optional, default is true
        # After copying the image, write the digest of the resulting image to the file. By default, the filename will be determined from the image and tag. The contents of this file are the digest output.
        #digestfile: # optional
        # Extra args to be passed to podman push. Separate arguments by newline. Do not use quotes - @actions/exec will do the quoting for you.
        #extra-args: # optional
